version: "3.0"

services:
  # lb:
  #   image: haproxy
  #   container_name: proxy
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./haproxy:/usr/local/etc/haproxy
  #   depends_on:
  #     - server

#  nginx:
#    image: nginx:latest
#    ports:
#      - "3000:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  haproxy:
    image: haproxytech/haproxy-alpine
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro
    depends_on:
      - server1
      - server2
#    networks:
#      - coding-pal-network

  server1:
    image: coding-pal:1.0
    restart: always
    depends_on:
      - redis
  #    ports:
#      - "8080:8080"
#    networks:
#      - coding-pal-network

  server2:
    image: coding-pal:1.0
    restart: always
    depends_on:
      - redis
  #    ports:
#      - "8080:8080"
#    networks:
#      - coding-pal-network
#    deploy:
#      replicas: 2
##      resources:
##        limits:
##          cpus: '0.1'
##          memory: 10M
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
#networks:
#  coding-pal-network: